return {
	{
		"rose-pine/neovim",
		opts = {
			highlight_groups = {
				Comment = { fg = "#6e6a86", italic = true },
				Keyword = { fg = "love" },
				Statement = { fg = "love" },
				Conditional = { fg = "love" },
				Repeat = { fg = "love" },
				Exception = { fg = "love" },
				Constant = { fg = "gold" },
				Number = { fg = "iris" },
				Float = { fg = "iris" },
				String = { fg = "leaf" },
				Character = { fg = "rose" },
				Function = { fg = "pine" },
				Special = { fg = "rose" },
				Type = { fg = "leaf" },
				StorageClass = { fg = "iris" },
				Structure = { fg = "leaf" },
				Tag = { fg = "love" },
				["@field"] = { fg = "iris" },
				["@property"] = { fg = "iris" },
				["@variable.member"] = { fg = "iris" },
				["@module"] = { fg = "foam" },
				["@string"] = { fg = "leaf" },
				["@string.regexp"] = { fg = "pine" },
				["@string.escape"] = { fg = "rose" },
				["@string.special"] = { fg = "leaf" },
				["@character"] = { fg = "rose" },
				["@function"] = { fg = "pine" },
				["@function.builtin"] = { fg = "foam" },
				["@function.method"] = { fg = "foam" },
				["@function.method.call"] = { fg = "foam" },
				["@constructor"] = { fg = "rose" },
				["@keyword"] = { fg = "love" },
				["@keyword.function"] = { fg = "love" },
				["@keyword.return"] = { fg = "love" },
				["@keyword.conditional"] = { fg = "love" },
				["@keyword.conditional.ternary"] = { fg = "love" },
				["@keyword.repeat"] = { fg = "love" },
				["@keyword.exception"] = { fg = "love" },
				["@keyword.import"] = { fg = "pine" },
				["@keyword.directive"] = { fg = "iris" },
				["@type"] = { fg = "leaf" },
				["@type.builtin"] = { fg = "foam" },
				["@type.definition"] = { fg = "leaf" },
			},
		},
	},
}
